[prune]
   non-go = true
   go-tests = true
   unused-packages = true

[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.19.0"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.19.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"